[package]
name = "deeplearn"
version = "0.1.0"
authors = ["Theodore DeRego <tderego94@gmail.com>"]

[dependencies.gpuarray]
git = "https://github.com/tedsta/gpuarray-rs"

[dependencies]
rand = "*"
num = "*"
